vich_uploader:
    db_driver: orm

    mappings:
       files_compagny:
           uri_prefix: /files/files_compagny
           upload_destination: '%kernel.project_dir%/public/files/files_compagny'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    
       files_user:
           uri_prefix: /files/files_user
           upload_destination: '%kernel.project_dir%/public/files/files_user'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
